/* LAB 3 -- OBJECTIVE -- Create 3 different methods that will calculate basic math formulas you use every day.
Ex: Average a set up numbers. calculating a square number, adding 20% to a bill

-------------------------------------------------------------*/

/*
Name: Patricia Antlitz
Date: 9/23/2021
*/
import java.util.Scanner;

public class MyFormulas_PatriciaAntlitz
{//open class

/* double variable will hold the values to be used on the calculations of a percentage of a given ammount
*
*  int firstNum, sec num, thridNum, averageNum, will hold the values to calculate the average of three numbers
*
*  int totalMult, multOne, multTwo will hold to values and the product of these two numbers
* */
    double percentIncrease, totalBill, totalPercentage, tipsTotal, percentCalc;
    int firstNum, secNum, thirdNum, averageNum;
    int totalMult, multOne, multTwo;

    // method sets all values to calculate the average of three numbers
    public void setAverageNum()
    {
        // will allow values to be entered by the user
        Scanner scnr = new Scanner(System.in);

        //lets the user know what this method will do and asks for the values required
        System.out.println("\nCalculate the average of three numbers.\n");
        System.out.println(" Enter the three numbers separed by a space: ");

        //scans user's entries and store them in the variables
        firstNum = scnr.nextInt();
        secNum = scnr.nextInt();
        thirdNum = scnr.nextInt();

        // calculates the average number of the three numbers entered by the user
        averageNum = (firstNum + secNum + thirdNum) / 3;
    }

    // this method will get the calculation performed on setAverage number and add it to a string to be printed
    public String getAverageNum()
    {
        String averagePhrase = "\n The average of " + firstNum + ", " + secNum + " and " + thirdNum +
                " is approximally: \n" + averageNum + "\n\n";
        // returns the string to allow it to be used at main
        return averagePhrase;
    }

    // method that sets the values for the variables
    public void setPercentIncrease()
    {
        // will scan user's entries
        Scanner scnr = new Scanner(System.in);

        // lets user know what the program is about and asks the user to enter to bill's total
        System.out.println("Calculate the tips on a bill.\n");
        System.out.println(" Enter the total of the bill: ");

        // totalBill is the cost (total) of the original bill enterd by the user
        totalBill = scnr.nextDouble();

        System.out.println(" Enter the desired percentage: (E.g. Enter 20 for 20%)");

        // totalPercentage = holds the percentage given by the user
        totalPercentage = scnr.nextDouble();

        // turns the given percentage into a decimal point to be multiplied by the totalBill
        percentCalc = totalPercentage / 100;

        // tipsTotal gets the difference when the tips are added
        tipsTotal = totalBill * percentCalc;

        // percentIncrease is the total of the "bill" plus the percentage
        percentIncrease = totalBill + tipsTotal;

    }

    // gets the information created at serPecentIncrease()
    public String getPercentIncrease()
    {
        // will print a phrase will all the values stored on the given variables
        String percentPhrase;
        percentPhrase = "\n Your bill of " + String.format("%.2f", totalBill) + " will increase by " +
                String.format("%.2f", tipsTotal) + " for a total of " + String.format("%.2f", percentIncrease) + "\n\n";
        // allows the variable to be used
        return percentPhrase;
    }

    // will calculate the product of two numbers
    public void setTotalMult()
    {
        //allows user's entries
        Scanner scnr = new Scanner(System.in);

        //method's intro
        System.out.println("\nCalculate the product of two numbers.\n");
        System.out.println(" Enter the two numbers separed by a space: ");

        // user entrie's assignment
        multOne = scnr.nextInt();
        multTwo = scnr.nextInt();

        //calculated the product of the two numbers given by the user
        totalMult = multOne * multTwo;
    }

    // gets the values generated by setTotalMult and adds it to a string variable
    public String getTotalMult()
    {
        String multPhrase = "\n The product of " + multOne + " x " + multTwo + " is equal to = \n" + totalMult + "\n\n";
        return multPhrase;
    }

    //main function call, execution
    public static void main(String args[])
    {//open main method
        // objects created for the average number, percentage of bill and product methods
        MyFormulas_PatriciaAntlitz averageMethod = new MyFormulas_PatriciaAntlitz();
        MyFormulas_PatriciaAntlitz percentageMethod = new MyFormulas_PatriciaAntlitz();
        MyFormulas_PatriciaAntlitz multiplicationMethod = new MyFormulas_PatriciaAntlitz();

        // calls method
        averageMethod.setAverageNum();
        // prints string stored at getAverageNum
        System.out.println(averageMethod.getAverageNum());

        percentageMethod.setPercentIncrease();
        System.out.printf(percentageMethod.getPercentIncrease());

        multiplicationMethod.setTotalMult();
        System.out.printf(multiplicationMethod.getTotalMult());

    }
} // end of program.